#include "MapGenParameters.h"

int32 MAIN_CHAIN_MIN;
int32 MAIN_CHAIN_RAND;
int32 EXT_LENGTH;

int32 ROOM_WIDTH;
int32 ROOM_LENGTH;
int32 TILE_SIZE;
int32 DOOR_OFFSET;

float TEMPLATE_SIZE_RATIO;
float PATH_POINT_DIST;
float ROOM_COVERAGE_MAX;
float RAND_WALL_CHANCE;
float RAND_WALL_WIDTH_SIZE_RATIO;
float RAND_WALL_LENGTH_SIZE_RATIO;

FMapGenParameters::FMapGenParameters() {}
